=== yduchesne/sapia/src/main/dtd/magnet-2.0.dtd
<!--
    Magnet configuration file DTD, version 2.0
    Author: Jean-Cedric Desrochers
    
    This file contains the definitions of a Magnet configuration file.
    
    XML document that conform to this DTD should declare the following doctype:
    
    <!DOCTYPE magnet PUBLIC "-//SAPIA OSS//Magnet DTD 2.0//EN"
                     "http://www.sapia-oss.org/dtd/magnet-2.0.dtd"> 

-->

<!ELEMENT magnet ((protocolHandlerDef | scriptHandlerDef | launchHandlerDef)*,
                  script*, (parameters | codebase | classpath | environment)*,
                  launcher*)>

<!ATTLIST magnet xmlns       CDATA #FIXED 'http://schemas.sapia-oss.org/magnet/'>
<!ATTLIST magnet name        CDATA #REQUIRED>
<!ATTLIST magnet description CDATA #IMPLIED>
<!ATTLIST magnet extends     CDATA #IMPLIED>


<!--
    Extension point to plug in your own protocols to resolve and load resources.
    By default Magnet handles the file and http schemes - corresponding to the
    file system and HTTP protocols.
-->
<!ELEMENT protocolHandlerDef EMPTY>

<!ATTLIST protocolHandlerDef type      CDATA #REQUIRED>
<!ATTLIST protocolHandlerDef classname CDATA #REQUIRED>


<!--
    Extension point to plug in your own scripting engine. Magnet comes with
    Beanshell (http://www.beanshell.org) integration built-in.-->
<!ELEMENT scriptHandlerDef EMPTY>

<!ATTLIST scriptHandlerDef type      CDATA #REQUIRED>
<!ATTLIST scriptHandlerDef classname CDATA #REQUIRED>


<!--
    Extension point to plug in your own class that launches applications. Magnet
    offers a java and a system launcher (to start Java and native processes, respectively).
-->
<!ELEMENT launchHandlerDef EMPTY>

<!ATTLIST launchHandlerDef type      CDATA #REQUIRED>
<!ATTLIST launchHandlerDef classname CDATA #REQUIRED>


<!--
    A Magnet configuration can contain various script elements to perform intialization tasks. At runtime
    Magnet will render and execute the script that matches the execution profile. If no script is
    provided for the profile and a script exists for the default one, it will be executed. Only one
    script by profile can exist within a Magnet configuration.
-->
<!ELEMENT script (#PCDATA)>
<!ATTLIST script type              CDATA #REQUIRED>
<!ATTLIST script profile           CDATA #IMPLIED>
<!ATTLIST script isAbortingOnError (true | false) "false">


<!--
    To define global parameters within the Magnet. Parameters can be specified for a given
    profile or for all profiles (called the default profile).
-->
<!ELEMENT parameters ( param+ )>

<!ATTLIST parameters profile CDATA #IMPLIED>


<!--
    Each param child element defines a given variable.
-->
<!ELEMENT param EMPTY>

<!ATTLIST param name   CDATA #REQUIRED>
<!ATTLIST param value  CDATA #REQUIRED>
<!ATTLIST param scope  (magnet | system) "magnet">
<!ATTLIST param if     CDATA #IMPLIED>
<!ATTLIST param unless CDATA #IMPLIED>


<!--
    A path element can be used to define a list of resources that are used in a given
    context (defining the classpath of a Java application, for example).
-->
<!ELEMENT path (include*, exclude*)>

<!ATTLIST path protocol  CDATA "file">
<!ATTLIST path host      CDATA #IMPLIED>
<!ATTLIST path directory CDATA #IMPLIED>
<!ATTLIST path sorting   (ascending | descending) #IMPLIED>


<!--
    Define resources to include in a path.
-->
<!ELEMENT include EMPTY>

<!ATTLIST include pattern CDATA #IMPLIED>


<!--
    Define resources to exclude from a path.
-->
<!ELEMENT exclude EMPTY>

<!ATTLIST exclude pattern CDATA #IMPLIED>


<!--
    Provides a convenient way to define the java.rmi.server.codebase system property .
-->
<!ELEMENT codebase (path+)>

<!ATTLIST codebase profile CDATA #IMPLIED>


<!--
    The classpath element allows defining the classpath of a Java application. It provides
    a convenient and elegant way to declare what are the files or resource directories
    that are needed as part of an application's classpath. 
-->
<!ELEMENT classpath (path*)>

<!ATTLIST classpath id     CDATA #IMPLIED>
<!ATTLIST classpath parent CDATA #IMPLIED>


<!--
    The environment element defines a group of variables that is passed to the system launcher
    as environment variables.
-->
<!ELEMENT environment (variable+)>

<!ATTLIST environment id     CDATA #IMPLIED>
<!ATTLIST environment parent CDATA #IMPLIED>


<!--
    The variable element defines a name-value pair that corresponds to an environment variable.
-->
<!ELEMENT variable EMPTY>

<!ATTLIST variable name  CDATA #REQUIRED>
<!ATTLIST variable value CDATA #REQUIRED>


<!--
    The launcher element defines how to launch (or start) a process with Magnet. It supports
    two types of launcher. The "java" type will use the Java reflexion API to dynamically call
    the main(String[] args) method of the specified class. The other supported type is "system"
    which creates a command string and executes it at the OS level using the Java
    Runtime.getRuntime().exec() method. Custom launchers can be introduced with the launchHandlerDef
    element (see documentation).
-->
<!ELEMENT launcher ( profile+ )>

<!-- Common attributes for launchers -->
<!ATTLIST launcher type      CDATA #REQUIRED>
<!ATTLIST launcher name      CDATA #REQUIRED>
<!ATTLIST launcher default   CDATA #IMPLIED>
<!ATTLIST launcher waitTime  CDATA #IMPLIED>

<!-- Attributes for java launcher -->
<!ATTLIST launcher mainClass CDATA #IMPLIED>
<!ATTLIST launcher args      CDATA #IMPLIED>
<!ATTLIST launcher isDaemon  (true | false) "false">

<!-- Attributes for system launcher -->
<!ATTLIST launcher command          CDATA #IMPLIED>
<!ATTLIST launcher workingDirectory CDATA #IMPLIED>
<!ATTLIST launcher os               CDATA #IMPLIED>


<!--
    The profile element defines the configuration of the launcher for a given profile. It provides a
    way to define parameters specific to the launcher type (like the classpath for "java" launchers
    and environment variables for "system" launchers).
-->
<!ELEMENT profile (parameters?, (classpath | environment?))>

<!ATTLIST profile name CDATA #REQUIRED>

=== yduchesne/sapia/etc/AllInOneTimeServerMagnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magnet PUBLIC "-//SAPIA OSS//Magnet DTD 2.0//EN"
                 "http://www.sapia-oss.org/dtd/magnet-2.0.dtd"> 

<magnet xmlns="http://schemas.sapia-oss.org/magnet/" extends="etc/GenericUbikMagnet.xml"
        name="AllinOneTimeServer" description="This magnet start all the processes to run the JNDI and time ever as well as the client">

  <!-- Define a java launcher that will start the Ubik JNDI server. -->
  <launcher type="java" name="jndiServer" mainClass="org.sapia.ubik.rmi.naming.remote.JNDIServer"
            args="${jndi.portNumber} ${jndi.domainName}" default="remote" isDaemon="true" waitTime="5000">

      <!-- Defines the example profile of this launcher. -->
      <profile name="remote">
        
          <!-- Defines the example message to send to the java app. -->
          <parameters>
              <param name="jndi.domainName" value="sapia"/>
          </parameters>

          <!-- Defines the classpath of the ubik example jars. -->
          <classpath>
            <path directory="${magnet.home}/lib/examples">
              <include pattern="*.jar" />
            </path>
          </classpath>
      </profile>
  </launcher>

  <!-- Define a java launcher that will start the stateless time server. -->
  <launcher type="java" name="timeServer" mainClass="org.sapia.ubik.rmi.examples.time.StatelessTimeServer"
            args="${timeServer.jndiUrlProvider} ${timeServer.jndiInitialFactory}" default="colocated" isDaemon="true" waitTime="5000">

      <!-- Defines the example profile of this launcher. -->
      <profile name="colocated">
          <parameters>
            <param name="timeServer.jndiUrlProvider" value="ubik://localhost:${jndi.portNumber}" />
            <param name="timeServer.jndiInitialFactory"
                   value="org.sapia.ubik.rmi.naming.remote.RemoteInitialContextFactory" />
          </parameters>
        
          <!-- Defines the classpath of the ubik example jars. -->
          <classpath parent="ubik">
            <path directory="${magnet.home}/lib/examples">
              <include pattern="*example*.jar" />
            </path>
          </classpath>
      </profile>

      <!-- Defines the example profile of this launcher. -->
      <profile name="remote">
          <parameters>
            <param name="timeServer.jndiUrlProvider" value="ubik://localhost:${jndi.portNumber}" />
            <param name="timeServer.jndiInitialFactory"
                   value="org.sapia.ubik.rmi.naming.remote.RemoteInitialContextFactory" />
          </parameters>
        
          <!-- Defines the classpath of the ubik example jars. -->
          <classpath>
            <path directory="${magnet.home}/lib/examples">
              <include pattern="*.jar" />
            </path>
          </classpath>
      </profile>
  </launcher>

  <!-- Define a java launcher that will start the time client application. -->
  <launcher type="java" name="timeClient" mainClass="org.sapia.ubik.rmi.examples.time.EndlessTimeClient"
            default="colocated" waitTime="5000">

      <!-- Defines the example profile of this launcher. -->
      <profile name="colocated">
          <!-- Defines the classpath of the ubik example jars. -->
          <classpath parent="ubik">
            <path directory="${magnet.home}/lib/examples">
              <include pattern="*example*.jar" />
            </path>
          </classpath>
      </profile>

      <!-- Defines the example profile of this launcher. -->
      <profile name="remote">
          <!-- Defines the classpath of the ubik example jars. -->
          <classpath>
            <path directory="${magnet.home}/lib/examples">
              <include pattern="*.jar" />
            </path>
          </classpath>
      </profile>
  </launcher>
</magnet>

=== yduchesne/sapia/tags/sapia_corus_parent-4.2-RC3/samples/corus_sample_magnet/src/main/resources/echo_server.magnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magnet PUBLIC "-//SAPIA OSS//Magnet DTD 2.0//EN"
                 "http://www.sapia-oss.org/dtd/magnet-2.0.dtd"> 

<magnet name="echo_server" description="Sample Echo Server"
        xmlns="http://schemas.sapia-oss.org/magnet/">

    <!-- Scripting the creation and definition of ${log.home} -->
    <script type="bsh" isAbortingOnError="true">
        import java.io.File;
  
        // Set log.home system property.
        String logHome = System.getProperty("user.dir") + "/log/" + System.getProperty("corus.process.profile");
        System.setProperty("log.home", logHome);
      
        // Creating log directory
        File logDir = new File(logHome);
        logDir.mkdirs();
        
        if (!logDir.exists()) {
          System.err.println("Could not create log directory: " + logDir.getAbsolutePath());
        }  
    </script>

    <!-- Define some system parameters -->
    <parameters>
        <param name="soto.debug"               value="true" scope="system" />
        <param name="java.net.preferIPv4Stack" value="true" scope="system" />
        
        <param name="echoServer.loopIntervalMillis" value="1000" scope="magnet" />
    </parameters>
    
    <classpath id="main-cp">
        <path directory="${user.dir}/lib">
            <include pattern="**/*.jar" />
        </path>
    </classpath>
    
    <!-- Launcher for the TIC echo server -->
    <launcher type="java" name="echo_server_tic" isDaemon="false"
              mainClass="org.sapia.corus.sample.EchoMain" args="TIC ${param.initialWaitDelayMillis} ${echoServer.loopIntervalMillis}">

        <profile name="dev">
            <parameters>
                <!--  Make tic starting before toc -->
                <param name="param.initialWaitDelayMillis" value="0" />
            </parameters>
            <classpath parent="main-cp" />
        </profile>

        <profile name="prod">
            <parameters>
                <!--  Make tic starting after toc -->
                <param name="param.initialWaitDelayMillis" value="2000" />
            </parameters>
            <classpath parent="main-cp" />
        </profile>
    </launcher>
    
    <!-- Launcher for the TOC echo server -->
    <!-- Running two main classes within the same VM -->
    <launcher type="java" name="echo_server_toc" isDaemon="false"
              mainClass="org.sapia.corus.sample.EchoMain" args="TOC 1500 ${echoServer.loopIntervalMillis}">

        <profile name="dev">
            <classpath parent="main-cp" />
        </profile>

        <profile name="prod">
            <classpath parent="main-cp" />
        </profile>
    </launcher>
    
</magnet>

=== yduchesne/sapia/trunk/magnet/etc/mainMagnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magnet PUBLIC "-//SAPIA OSS//Magnet DTD 2.0//EN"
                 "http://www.sapia-oss.org/dtd/magnet-2.0.dtd"> 

<magnet xmlns="http://schemas.sapia-oss.org/magnet/" name="MainTestMagnet" description="Test extended magnet with a system launcher">

    <!-- We use a bean shell script to create a directory on the file system. -->
    <script type="bsh" isAbortingOnError="true">
        File aFile = new File(System.getProperty("user.dir")+ "/temp",
                              String.valueOf(System.currentTimeMillis()));

        System.out.println("BSH SCRIPT: Creating temp directory " + aFile.getAbsolutePath());
        aFile.mkdirs();
    </script>

    <!-- Define global properties -->
    <parameters>
        <param name="RootMagnet" value="mainMagnet.xml" />
        <param name="SystemRoot" value="C:\Windows" />
        <param name="message.profile" value="default" scope="system"/>
    </parameters>

    <!-- Define properties used only when the profile dev is executed -->
    <parameters profile="dev">
        <param name="message.profile" value="dev" />
    </parameters>

    <!-- Define variable used only when the profile test is executed -->
    <parameters profile="test">
        <param name="message.profile" value="test" />
    </parameters>

    <!-- Define environment variables that will be used when starting the system launcher.
         The set of environment variables is identified by the name root -->
    <environment id="root">
        <variable name="OS" value="Windows" />
    </environment>

    <!-- Define environment variables that will be used when starting the system launcher.
         The set of environment variables is identified by the name windows_env and extends
         it's parent environment 'root' -->
    <environment id="windows_env" parent="root">
        <variable name="ComSpec" value="${SystemRoot}\system32\cmd.exe" />
        <variable name="CommonProgramFiles" value="&quot;C:\Program Files\Common Files&quot;" />
        <variable name="SystemRoot" value="${SystemRoot}" />
        <variable name="windir" value="${SystemRoot}" />
    </environment>

    <!-- This system launcher will only work on a Windows box. It executes the net
         send command sending the message generated by the profile. A default profile
         is define so if we use the test profile, the launcher still run. -->
    <launcher type="system" os="windows" name="netSend" command="cmd /C start /B net send * ${message}" default="dev2">
        <profile name="dev">
            <!-- We define properties local to this launcher. The message property is use in the
                 command of the system command that it will be executed. -->
            <parameters>
                <param name="message" value="Hello from profile ${message.profile}" />
            </parameters>
            
            <!-- To pass environment variables to the system process we will spawn. We refer to the
              	 windows_env set define earlier as the parent and we override values for testing. -->
            <environment parent="windows_env" >
              <variable name="OS" value="${os.name}" />
              <variable name="windir" value="${SystemRoot}2" />
              <variable name="linux" value="rocks!" />
            </environment>
        </profile>
    </launcher>

</magnet>
